plugins {
    id 'java'
}

targetCompatibility = 6
sourceCompatibility = 6

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://repo.spongepowered.org/maven/' }
}

dependencies {
    implementation project(':common')

    compileOnly files('../libs/javassist-java5.jar')
    compileOnly('net.fabricmc:fabric-loader:0.15.3')
    compileOnly('org.spongepowered:mixin:0.8.5')
    compileOnly('org.ow2.asm:asm-tree:9.5')
}