plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '6.1.0'
}

group 'uk.betacraft'
version '2.0'

subprojects {
    apply plugin: 'java'

    processResources {
        def tokens = [version: "${rootProject.version}-${new Date().format('yyyyMMdd')}"]
        filesMatching('*mod*') { expand tokens }
        filesMatching('version.txt') { expand tokens }
    }
}

dependencies {
}

shadowJar {
    configurations = [project(':common').configurations.runtimeClasspath]
    from project(':common').jar
    from project(':fabric').jar
    from project(':fml').jar
    from project(':risugami').jar
    relocate('org.objectweb.asm', 'uk.betacraft.legacyfix.shadowed.org.objectweb.asm')
}

jar {
    dependsOn(shadowJar)

    manifest {
        attributes(
            'TweakClass': 'uk.betacraft.legacyfix.tweaker.LFTweaker',
            'Main-Class': 'uk.betacraft.legacyfix.LegacyFixLauncher',
            'Premain-Class': 'uk.betacraft.legacyfix.Agent',
            'Can-Redefine-Classes': 'true',
            'Can-Retransform-Classes': 'true',
            'FMLCorePlugin': 'uk.betacraft.legacyfix.fml.CpwCoreMod'
        )
    }
}