plugins {
    id 'java'
}

targetCompatibility = 6
sourceCompatibility = 6

repositories {
    mavenCentral()
}

sourceSets {
    api {
        java {
            srcDir 'src/api/java'
        }
    }
}

dependencies {
    implementation project(':common')
    compileOnly sourceSets.api.output

    compileOnly files('../libs/javassist-java5.jar')
}