name: Java CI with Gradle

on:
  push:
    branches: [ develop, stable ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - name: Set up JDK 8
      uses: actions/setup-java@v3.9.0
      with:
        java-version: 8
        distribution: zulu
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        path: build/libs